version: '3'

services:

  redis:
    image: redis:3.0
    command: ['redis-server', '--requirepass T2LvfRjmRAYntqmOUh7DTbviNn']
    expose:
      - 6379
    ports:
      - "9737:6379"

  mysql:
    image: mysql:5.6
    command: [mysqld, --character-set-server=utf8, --collation-server=utf8_bin]
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "7033:3306"